server:
  port: 7979

spring:
  datasource:
    url: jdbc:mysql://8.129.68.125:3306/demo1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  redund:
    mapper-locations: classpath*:mappeing-json/*.json

